Repository rachelbuchta/refactor_tractor, pull requests merged in 2021-01, with the labels that each got.

#20 Feature fix search function
  src/data/recipe-data.js
  src/scripts.js
  test/recipe-test.js
  test/user-test.js
Labels: bug fix, help wanted

#24 Feat/display images
  package-lock.json
  src/css/styles.scss
  src/index.html
  src/index.js
  src/recipe.js
  src/scripts.js
  src/user.js
Labels: bug fix

#31 Feature pantry tests
  src/data/ingredient-data.js
  src/data/ingredient-test-data.js
  src/data/recipe-test-data.js
  src/data/users-test-data.js
  src/scripts.js
  test/pantry-test.js
Labels: documentation, enhancement

#44 Feature pantry class
  src/data/users-test-data.js
  src/pantry.js
  src/user.js
  test/pantry-test.js
Labels: enhancement

#63 Feature pantry class
  src/pantry.js
  src/user.js
  test/pantry-test.js
  test/recipe-repo-test.js
Labels: enhancement
